name: Release templates
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}